### ISSUE TITLE
can't create app with "App Manager" credentials

### ISSUE THREAD

**Issue by dtgallant** [fastlane/produce#103]
Are itunesconnect users of type "App Manager" unable to create new apps at this point?  Works fine with the itunesconnect Team Agent user.

If not currently available is this an upcoming feature?

thanks,

**Comment by backslash-f** [comment]
Yeah, I have the same question. For me, the returned error message is:

`/Users/fernando/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spaceship-0.19.1/lib/spaceship/portal/ui/select_team.rb:37:in`select_team': Your account is in no teams (RuntimeError)`

Which is not true, since I can login with that account in iTunes Connect and manage apps (app manager role).

Thanks.

**Comment by vpolouchkine** [comment]
Can you guys try running `sudo gem update spaceship`?

**Comment by backslash-f** [comment]
Hi. Thanks for taking a look at this issue.

Ok, just did. Same error: "[!] Your account is in no teams (RuntimeError)"

Am I doing this right?

`produce CREATE -u myAppleId@mail.com -a com.trippergroup.test -q AppTest -z '1.0' -k 'myiTunesConnectTeamID'`

I enabled the crash report. Here it is:
_Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '45cb84dea4c1d840512603c35d6bc0c0'_

Thank you.

**Comment by KrauseFx** [comment]
@Conaaando What happens when you login manually on the Developer Portal and iTunes Connect? You'll probably see some kind of error.

**Comment by backslash-f** [comment]
Hi @KrauseFx!

No errors whatsoever. Here is a screenshot of that user logged on **iTunes Connect**:

http://cl.ly/1n1L2v1C3F1B

If I click on "My Apps", the list of apps under that account is shown. And I can manage them. Change their info, for example.

Now if I login on the **Developer Portal**, I can see the following message (expected):

_Your Developer Program has expired.Please visit the Programs & Add-Ons section to renew your membership._

I mean 'expected' because this is not the main account. It's an "app manager account", invited by the main one.

Would this be a supported scenario?

Or: should an Apple ID -- that is not enrolled in the developer program, but is part of a team as "App Manager" -- be allowed to create new app entries in iTunes Connect via Produce?

Thanks!

**Comment by KrauseFx** [comment]
> Your Developer Program has expired.Please visit the Programs & Add-Ons section to renew your membership.

That's why `produce` is not working

**Comment by backslash-f** [comment]
All right. So I think what @dtgallant mentioned is correct: itunesconnect users of type "App Manager"  are unable to create new apps at this point. It works fine with the itunesconnect Team Agent user tho (same here).

Would that be an upcoming feature?

Thanks.

**Comment by KrauseFx** [comment]
If it's not possible on iTC there is nothing `spaceship`/`produce` can do.

**Comment by backslash-f** [comment]
Ok. Just to make it clear: it **IS** possible for that account to create a new app in ITC via web:

http://cl.ly/1O1P2M1I0c0v (taken just now)

The very same account is unable to do the same via spaceship/produce.
