### ISSUE TITLE
Allow to delete an app

### ISSUE THREAD

**Issue by patoroco** [fastlane/produce#94]
Hi,

I was playing with produce to prepare a talk about fastlane tools, and I finished with several test-apps on my iTunes Connect dashboard :(

I was reading about how to delete apps, and apple doesn't allow to delete brand new apps  (without any published version), so maybe should be good to add this STUPID 'detail' to produce documentation. Link: https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/TransferringAndDeletingApps.html

Also, should be good to have a `delete_app` action in produce when you have correct permissions, what do you think?

**Comment by KrauseFx** [comment]
Not sure, in general all fastlane tools don't do anything destructive. What do you recommend adding to the README?

**Comment by wkoszek** [comment]
@patoroco Same problem here.
@KrauseFx is there an API for 'delete' functionality? It'd be very helpful, since iTunes Connect doesn't have "Delete" a button after you create an app. So I made `HelloWorld` and some other toy apps for testing, but have no way to clean it up. I would be OK with destructive+verbose stuff, since you already have to know what you're doing with stuff like `fastlane`.
